### PR TITLE
Add historic materials recovered from Amiga disk backup images.

### PR DESCRIPTION
**Pull request by cpressey**

### CODE REVIEW

**Comment by j4james** [comment]
I find this historic stuff fascinating. It's interesting to see that these versions didn't yet support wrapping around the boundaries of the playfield and also didn't have the greater-than command.

If you're looking for other historic versions, I found a copy of the version 1.01 source on an old version of your website in the [Internet Archive](https://web.archive.org/web/20010614052854/http://www.catseye.mb.ca:80/esoteric/befunge/93/dllcall.zip), and you posted a copy of the version 2.00 source (at least bef.c) on the [Befunge mailing list](http://frox25.no-ip.org/%7Emtve/tmp/bef_maillist_0_520.txt) (just search for bef.c).

**Comment by wimrijnders** [comment]
I just had to look and lo and behold I'm on that mailing list. First post on `Fri, 02 May 1997`, and I was pretty active. In Internet Time, that's like encountering yourself in the Middle Ages. Memories...

**Comment by cpressey** [comment]
My word.

a) I wasn't aware of that mailing list archive. I was aware of [this file](http://web.archive.org/web/20000817233201/http://www.catseye.mb.ca/esoteric/befunge/bfml.zip), which was on www.catseye.mb.ca, and which archive.org *partially* retained - you can run a zip-repair tool on it and unzip it to get some emails. I don't know how much these two archives overlap (the content is far too embarrassing to read without considerable preparation beforehand, you understand) but if they aren't the same, that's a significant amount of history.

b) I guess we should thank whoever put together the DLL-calling version (I want to say Kevin Vigor but I could be wrong) for trapping a copy of 1.01 in it (slightly refactored into multiple source files, but otherwise unchanged.)

c) I did not realize until now that the version I've called "1.0rc1" doesn't actually do wrapping! That strongly suggests it really is a very early version, quite possibly the initial version I threw together after getting the idea, because I've always thought of toroidal wrapping as something that was there from the start. All I remember about wrapping in Befunge-93 is that I rather borrowed the idea from [Asteroids](https://en.wikipedia.org/wiki/Asteroids_(video_game)).

**Comment by j4james** [comment]
I hadn't seen that bfml.zip before. But being the Befunge fanatic that I am, I've now done a diff of those messages against mtve's copy of the mailing list. There are around 140 messages in the mtve list that aren't in your archive, and around 40 in your archive that aren't in the mtve list. I suspect some of those might actually have been private messages to you, but they're all Befunge related (well except for one spam email).

Probably the most interesting for me, historically speaking, was the notification you received in April 97 that your website had been chosen as Geek Site of the Day (which I believe was quite a major boost for Befunge at the time). There was also a message from Eric S. Raymond, saying your site had been listed in the [Retrocomputing Museum](http://www.catb.org/retro/), although I couldn't find any actual evidence of that. I do know Befunge is listed in [The Jargon File](http://www.catb.org/~esr/jargon/html/B/Befunge.html), and there's also a mention on his [Intercal page](http://www.catb.org/~esr/intercal/), so perhaps that is what he was referring to.

**Pull request merged**
